name: Testing
on:
  pull_request:
    branches:
    - main
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      # - name: Testing Swift package
      #   run: |
      - name: Testing iOS app
        run: |
          set -eo pipefail

          xcodebuild -workspace GMAPP.xcworkspace \
            -scheme GMAPP \
            -destination platform=iOS\ Simulator,OS=14.5,name=iPhone\ 12 \
            clean test | xcpretty